version: '3'
services:
  web:
    image: python:3.9
    ports:
      - "8050:8050"
    volumes:
      - C:/Users/Belisario/fintech_project:/app: /app
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fintech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
